# To run: conda env create -f environment.yml
name: nerd
channels:
    - conda-forge
    - nvidia
dependencies:
    - python=3.8
    - pip
    - cudatoolkit=11.2
    - cudnn=8.1
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    - imagemagick
    - openexr-python
    - pip:
          - pyexr==0.3.8
          - tensorflow==2.6.2
          - tensorflow-addons==0.14.0
          - opencv-python==4.4.0.42
          - scipy
          - pytest
          - tqdm
          - flake8
          - black
          - isort
          - ffmpeg-python
          - pylatex
          - scikit-image
          - pyquaternion
